### ISSUE TITLE
Wrong colorization after "type" even if it's not a standalone word

### ISSUE THREAD

**Issue by alfonsogarciacaro** [ionide/ionide-fsgrammar#103]
![syntax_color](https://user-images.githubusercontent.com/8275461/46480550-bdca5600-c7f1-11e8-907f-496716963622.gif)

**Comment by MangelMaxime** [comment]
I can't reproduce the problem with latest Ionide.

Can you please check if you have still have the problem in an empty file. Something like:

```fs
module Test

let self =
    if self.process_type <> OderToPay && self.process_type <> InvoiceToPay then
        ""
    else
        ""    
```

Or if my hand written code is testing the wrong thing :)

**Comment by alfonsogarciacaro** [comment]
Yes, unfortunately it's still happening :/ You can test with:

```fsharp
type Foo =
    { process_type: string }

let test() =
    let self = { process_type = "foo" }
    if self.process_type = "foo"
    then failwith "WTF!"
    else self
```

![syntax](https://user-images.githubusercontent.com/8275461/47153110-e61c7f00-d2de-11e8-8634-2014fe7bd686.gif)

**Comment by alfonsogarciacaro** [comment]
Ah, yeah! Uninstalled and reinstalled Ionide and it's working fine now. Weird, I thought extensions were automatically updated now. Sorry for the hassle!

**Comment by MangelMaxime** [comment]
No problem :)

Yes, sometimes I think VSCode is failing to update properly the extension. For example, sometimes I have some files missing...
