### ISSUE TITLE
Static val mutable

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-fsgrammar#104]
By @dustinmoris in https://github.com/ionide/ionide-vscode-fsharp/issues/923

---

Hi,

Not even sure if this is an Ionide issue, but I thought I'd raise it here and see if you think it should be moved somewhere else.

Currently (latest Ionide) I still get a lot of wrong syntax highlighting, e.g.:

![image](https://user-images.githubusercontent.com/4580714/45976686-5a953280-c03f-11e8-87fd-14310e5ded1c.png)

Is this something which can be improved easily? It's not a big issue, but something which would be nice to have working more consistently at some point.

Thank you!

If you need the code for testing:

```fsharp
let private MinimumCapacity = 5000
let private MaximumCapacity = 100000

type private StringBuilderPool =

    [<DefaultValue; ThreadStatic>]
    static val mutable private instance : StringBuilder

    [<DefaultValue; ThreadStatic>]
    static val mutable private created : DateTimeOffset

    static member Rent () =
        let lifetime = DateTimeOffset.Now - StringBuilderPool.created
        let expired  = lifetime > TimeSpan.FromMinutes 10.0
        let sb       = StringBuilderPool.instance
        if not expired && sb <> null then
            StringBuilderPool.instance <- null
            sb.Clear()
        else new StringBuilder(MinimumCapacity)

    static member Return (sb: StringBuilder) =
        if sb.Capacity <= MaximumCapacity then
            StringBuilderPool.instance <- sb
            StringBuilderPool.created  <- DateTimeOffset.Now
```

**Comment by MangelMaxime** [comment]
@Krzysztof-Cieslak I think this can be closed now

<img width="564" alt="capture d ecran 2018-10-31 a 10 53 31" src="https://user-images.githubusercontent.com/4760796/47780208-3e9a4600-dcfb-11e8-820e-3585774a4300.png">
