### ISSUE TITLE
Function named "eval" incorrectly highlighted

### ISSUE THREAD

**Issue by rmunn** [ionide/ionide-fsgrammar#11]
A function named "eval" will be highlighted correctly when it's defined. But when you call it, it will be highlighted as if the "val" part of the function is a keyword:

![incorrent-highlighting](https://cloud.githubusercontent.com/assets/90762/17283060/9bb414f8-57d6-11e6-8702-64a0bdb97d01.png)

I have also been able to reproduce this behavior with other functions that contain keywords inside their names, like `is_a_member`, as long as the "keyword" comes at the end of the name:

![incorrent-highlighting-2](https://cloud.githubusercontent.com/assets/90762/17283154/74cb916c-57d7-11e6-9830-06d387d56c4c.png)

Also, if the line is `eval (x + 4)`, then the function is highlighted correctly (the `val` part is not seen as a keyword). Only when the line looks like `eval x` does the highlighting get it wrong. In other words, when it would match a regex that looks like correct use of the `val` keyword.

Adding a simple "start-of-word" lookahead to the keyword regex will probably solve this issue.

**Comment by rmunn** [comment]
These screenshots were taken with ionide-fsharp extension 2.2.9 inside Visual Studio Code 1.3.1.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in bc313d72b81ed390f63f5536797c406977802a34
