### ISSUE TITLE
Syntax highlighting for let [<Literal>] broken 

### ISSUE THREAD

**Issue by forki** [ionide/ionide-fsgrammar#12]
![image](https://cloud.githubusercontent.com/assets/57396/17364682/eb0aa8bc-5981-11e6-96de-4fd65cf69617.png)

reposted from https://github.com/ionide/ionide-vscode-fsharp/issues/123#issuecomment-237213616

**Comment by TeaDrivenDev** [comment]
The issue I posted as https://github.com/ionide/ionide-vscode-fsharp/issues/281 looks like it's the same thing:

When using `let` with destructuring assignments for arrays, lists or tuples (with parentheses), it is not highlighted as a keyword and retains the default text color. The names being bound are also not highlighted.

With a simple tuple destructuring, coloring is correct:
`let a, b = 1, 2` has `let` highlighted as a keyword and `a` and `b` as names bound here.

Coloring does not work for the following:
```
let [| a; b |] = [| 1; 2 |]
let [ a; b ] = [1; 2]
let (a, b) = 1, 2
```
All of these will have `let` as well as `a` and `b` in the default text color.

**Comment by Krzysztof-Cieslak** [comment]
Attributes Fixed in https://github.com/ionide/ionide-fsgrammar/commit/e7b67398235e2634ec60f697fb6e03f19b24aefe

let deconstruction issue moved to #24
