### ISSUE TITLE
Ionide colorizes inline internal operator incorrectly

### ISSUE THREAD

**Issue by matthid** [ionide/ionide-fsgrammar#121]
Code:

```fsharp
    /// Backwards dependencies operator - x is dependent on ys.
    let inline internal (<==) x ys = Dependencies x ys
```

**Ionide**

Just open [Target.fs](https://github.com/fsharp/FAKE/blob/a5729d3f84949683f865842dfc8df7dcd181b97b/src/app/Fake.Core.Target/Target.fs#L318) in Ionide

![image](https://user-images.githubusercontent.com/1866463/56094030-bd60f500-5ecf-11e9-949b-c2b86e07cb91.png)

**Visual Studio 2017**
![image](https://user-images.githubusercontent.com/1866463/56094048-eaada300-5ecf-11e9-886b-4e2ed2b4af0e.png)

**Comment by matthid** [comment]
> I hope no :) 

Probably a stupid question, but why even do it this way when FCS provides an API for that?

**Comment by Krzysztof-Cieslak** [comment]
> Probably a stupid question, but why even do it this way when FCS provides an API for that?

Because VSCode doesn't give API for that :-)
