### ISSUE TITLE
{ new ... with } breaks syntax highlighting

### ISSUE THREAD

**Issue by debugnik** [ionide/ionide-fsgrammar#137]
After updating to 4.0.4, expressions of the form `{ new ... with }` break syntax highlighting.

When it's written in a single line, it only breaks highlighting for the keywords:

![code](https://user-images.githubusercontent.com/1218253/60761934-cfc47800-a053-11e9-994f-fddb27399fcb.png)

but it also breaks highlighting to the end of the file if written on multiple lines:

![code 2](https://user-images.githubusercontent.com/1218253/60761937-d94de000-a053-11e9-888f-0ac44c9c5a51.png)

**Comment by Krzysztof-Cieslak** [comment]
@MangelMaxime looks like the recent fix broken some other case :-(

**Comment by MangelMaxime** [comment]
Sorry about that...

We don't have a "test" for the `new ... with` syntax.

I am going to take a look at a fix for this issue and adding a test for it.

**Comment by debugnik** [comment]
I'm noticing that expressions like `use cts = new CancellationTokenSource()` cause the exact same behaviour. Removing `new` fixes it, so I guess the trigger for this issue is actually just the `new` keyword?

**Comment by MangelMaxime** [comment]
Yes, we added a new rule for `new` keywords in order to support the `struct` ["constructor"](https://github.com/ionide/ionide-fsgrammar/blob/master/sample-code/SampleKeywords.fs#L14).

But, I think it's going out of its scope.
