### ISSUE TITLE
The keyword "new" breaks the syntax highlighting.

### ISSUE THREAD

**Issue by teo-tsirpanis** [ionide/ionide-fsgrammar#140]
Before:
![A piece of source code without the `new` keyword](https://user-images.githubusercontent.com/12659251/61074561-aa9f8300-a420-11e9-8f79-8996eae7382c.png)

After:
![A piece of source code with the `new` keyword. Its highlighting completely breaks after that part.](https://user-images.githubusercontent.com/12659251/61074598-bbe88f80-a420-11e9-9c01-925c6fe93b6c.png)

I could have removed the `new`, but the compiler would complain because `StringReader` implements `IDisposable`.

**Comment by MangelMaxime** [comment]
Hello,
I fixed several issues related to `new` keyword in the past days can you please check that you are using the latest version of Ionide `4.0.5`?

And if no, can you please provide a textual representation for reproduction code.

**Comment by teo-tsirpanis** [comment]
Lol, I just saw the "Please reload to update" prompt when I opened the extensions pane. After the update, it works like a charm.
