### ISSUE TITLE
Method Call Coloring

### ISSUE THREAD

**Issue by g5becks** [ionide/ionide-fsgrammar#142]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Method call coloring.

**Additional context**
I'm coming from JetBrains rider and in that Ide, you can customize all token colors from inside the UI, but by default, all method calls are colored differently from the instance ( see below. )

![Screen Shot 2019-09-12 at 11 57 36 PM](https://user-images.githubusercontent.com/42525743/64836718-310b4900-d5b9-11e9-8aba-1d93157bac76.png)

I was wondering if this would be something that is hard to add to Ionide? It makes scanning the code much easier IMO.

Thanks.

**Comment by G5Becks** [comment]
Thanks for the response.

**Comment by MangelMaxime** [comment]
To complete, my answer I know that's it's possible to simulate highlighting based on Tokens using some of the VSCode API. But it's not officially supported and will require a lot of work and "hacks" to get themes information etc.

There is only one extension that I am aware of which does that right now.  If I remember correctly it's the C++ one.

**Comment by MangelMaxime** [comment]
After speaking with @Krzysztof-Cieslak, we will not use the same hack as C++ extension does. We are going to wait for VSCode to officially support semantic colourisation.

**Comment by jl0pd** [comment]
VSCode finally got [semantic colorization](https://code.visualstudio.com/updates/v1_45#_semantic-token-styling)!

**Comment by Krzysztof-Cieslak** [comment]
And, yes, we implement it already.
