### ISSUE TITLE
Multiline comments captures too greedily

### ISSUE THREAD

**Issue by catfly1** [ionide/ionide-fsgrammar#165]
**Describe the bug**
Prior to a recent update, the following code was correctly syntax highlighted by ionide, but now it appears to treat the proceeding definitions as half comment. This causes issues for projects using fsdocs, which make extensive use of multiline comment to perform doc operations.

```
(*** hide ***)
System.IO.Directory.SetCurrentDirectory __SOURCE_DIRECTORY__
#load @"../../../bootstrap/references.fsx"
open Refs
```

**Screenshots**
In summary it currently looks like this:
![after](https://user-images.githubusercontent.com/80320799/146107196-de239091-6d04-42d5-ac9b-7d886a4be39e.png)

When it used to look like this (for the same comment style):
![clean](https://user-images.githubusercontent.com/80320799/146107210-c79137eb-6edb-4228-8771-7e98a1e4bbce.png)

**Environment (please complete the following information):**
 - OS: Debian 11
 - Ionide version: v5.10.2
 - VSCode version: 1.63.1
 - dotnet SDK version: .net 6
 - mono / .Net Framework version: N/A

**Comment by catfly1** [comment]
Potentially related fix: https://github.com/ionide/ionide-fsgrammar/pull/164/files

**Comment by MangelMaxime** [comment]
I confirm that #164 fix this problem

**Comment by baronfel** [comment]
Thanks, will do 👍
