### ISSUE TITLE
Some bindings are missing?

### ISSUE THREAD

**Issue by njlr** [ionide/ionide-fsgrammar#172]
**Describe the bug**

This is an issue I noticed on _GitHub_, which [apparently](https://github.com/github/linguist/blob/master/vendor/README.md) uses this project. 

I believe that bindings for `use`, `use!`, `and` & `and!` are missing. 

**To Reproduce**

See the code below:

```fsharp
let x = 1

let rec y = 2
and z = 3

use d = new Disposable()

let f = 
  foo {
    let! a = bar
    and! b = qux

    use! c = fooBar

    ()
  }
```

**Expected behaviour**

All binding names should be highlighted. However, the following are not:

 - `z` (`and`)
 - `d` (`use`)
 - `b` (`and!`)
 - `c` (`use!`)

**Screenshots**

![Screenshot 2022-05-17 at 18-03-36 ionide_ionide-fsgrammar Shared Textmate Regex Style F# Language Grammar](https://user-images.githubusercontent.com/1577531/168870695-38d81f9f-14a3-41c7-9f6c-bba92a0b8892.png)
_(Screenshot of the above)_

**Environment (please complete the following information):**
 - OS: N/A
 - Ionide version: N/A
 - VSCode version: N/A
 - dotnet SDK version: N/A
 - mono / .Net Framework version: N/A

**Additional context**

None

**Comment by MangelMaxime** [comment]
I had a quick look at the issue and the fix should not be to difficult to implement.

I give it a try this evening or tomorrow.
