### ISSUE TITLE
Syntax highlighting breaks when returning a binding that begins with "use"

### ISSUE THREAD

**Issue by enriquein** [ionide/ionide-fsgrammar#180]
**Describe the bug**
Syntax highlighting breaks when you return a binding that begins with `use`. This started happening since the latest update to ionide. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a module or class and define two functions or methods
2. Create a binding on the first function/method and make sure the name begins with `use`. For this repro I used `user`.
3. Have the function return this binding.
4. Syntax highlight breaks.

I am including a gif below so you can see it in action.

**Expected behaviour**
Syntax highlighting should be able to work regardless of binding names.

**Screenshots**
Minimal repro gif. Notice how as I'm renaming or changing the return value, the word `user` only has the `use` part highlighted as well.

![highlight-bug-repro](https://user-images.githubusercontent.com/265092/183098119-88f76d67-61b5-4335-a2ea-67d346f65fec.gif)

**Environment (please complete the following information):**
 - OS: Windows 10 (Version 10.0.19044.1826)
 - Ionide version: 7.0.0
 - VSCode version: 1.70.0
 - dotnet SDK version: 6.0.302
 - mono / .Net Framework version: N/A

**Additional context**
For now I can work around it by avoiding the `use` prefix on bindings.

**Comment by baronfel** [comment]
This should be fixed by https://github.com/ionide/ionide-fsgrammar/pull/179, which just hasn't been released in an ionide update yet.
