### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xavierzwirtz** [ionide/ionide-fsgrammar#19]
Would it be possible to add a license to this project? I assume its MIT like the rest of ionide, just want to make sure though.

**Comment by Krzysztof-Cieslak** [comment]
Thanks for pointing it out, not sure how I've missed it.

yes, it's MIT, just uploaded file

**Comment by xavierzwirtz** [comment]
Thanks, I am basing a grammar off of `fsharp.json`, wanted to make sure I had it licensed right.
