### ISSUE TITLE
Infix multiplication operator is treated as block comment terminator

### ISSUE THREAD

**Issue by mbottini** [ionide/ionide-fsgrammar#207]
**Describe the bug**
Inside of a block comment, the infix multiplication operator `(*)` is treated as the terminator of a block comment. This is not correct; F# tokenizes keywords inside of comments, and since `(*)` is a keyword, it and the `*)` inside it is discarded.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a new F# file.
2. Type the following expression:
        
        (* This is a comment that include (*) This should also be a comment! *)

**Expected behaviour**
The syntax highlighter should associate the closing paren of the infix operator with its opening paren and not be associated with the paren that came before it.

**Screenshot**

![image](https://github.com/ionide/ionide-fsgrammar/assets/6901247/290f07a3-8ec0-4e5e-95ed-6f13e5055f74)

**Environment (please complete the following information):**
 - OS: Arch Linux, kernel v6.6.7. Desktop environment is GNOME.
 - Ionide version: v7.16.1
 - VSCode version: 1.85.1
 - dotnet SDK version: 8.0.100
 - mono / .Net Framework version: (N/A)

**Comment by mbottini** [comment]
(Sorry, completely new to this)

It looks like this should be two separate bugs, since the rules are handled in completely different parts of the grammar. The comment block bug is, I think, due to the regex that the grammar uses to detect `endCapture` here: https://github.com/ionide/ionide-fsgrammar/blob/master/grammars/fsharp.json#L559C40-L559C40

    (\\*+\\))

This should match iff the character that precedes this is not an opening parenthesis.

    ([^(]\\*+\\))

I need to figure out a development environment for iterating on my machine to confirm.

**Comment by baronfel** [comment]
@mbottini thanks for reporting and considering contributing! There are instructions to debug the changes in [CONTRIBUTING.md](https://github.com/ionide/ionide-fsgrammar/blob/master/CONTRIBUTING.md) - it _should_ just be F5'ing in the repo. There's a dummy extension that loads your changes.

**Comment by mbottini** [comment]
This part should be resolved by the pull request. I'm going to split off the other issue (the infix multiplication operator itself) into another issue.
