### ISSUE TITLE
Tuple and brackets can break highlighting for the remainder of the file

### ISSUE THREAD

**Issue by kojo12228** [ionide/ionide-fsgrammar#217]
**Describe the bug**
Something about having a tuple (`*`) and a token in brackets within a function parameter type breaks the syntax highlighting for the rest of the file.

**To Reproduce**

```fs
let baz 
    (qux : unit * ('T))
    =
    ()

let foo =
    match true with
    | true -> ()
    | false -> ()
```

**Expected behaviour**

Only the `'T` token should be coloured they way it is, but instead many of the remaining tokens are. Note, without the brackets there is no issue:

```fs
let baz 
    (qux : unit * 'T)
    =
    ()

let foo =
    match true with
    | true -> ()
    | false -> ()
```

**Screenshots**

It looks particularly bad in the Monokai theme:

![image](https://github.com/ionide/ionide-fsgrammar/assets/36001967/17e5aa83-a48a-4efb-8b83-d00a54545d09)

**Environment (please complete the following information):**
 - OS: Linux (Ubuntu 22.04)
- Ionide version: 7.20.1
- VSCode version: 1.90.1 (also reproducible in GitHub)

**Additional context**

This is a particularly annoying bug where brackets are important, but then break the rest of the file, for example:

```fs
let baz 
    (qux : unit * 'T -> 'T)
    =
    ()

let foo =
    match true with
    | true -> ()
    | false -> ()
```

The above is fine, but is different from below which is not:

```fs
let baz 
    (qux : unit * ('T -> 'T))
    =
    ()

let foo =
    match true with
    | true -> ()
    | false -> ()
```

I wonder if this is related to #183

**Comment by kojo12228** [comment]
I don't quite understand how TextMate grammars work, but using the [VSCode scope inspector](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector), I can see that with the additional brackets around `'T`, the entity scopes become the following:

```
entity.name.type.fsharp
binding.fsharp
source.fsharp.fsl
```

And for many of the tokens, `foreground`  it noted as `entity.name`.

I can't really see where `entity.name.type.fsharp` is defined and when inspecting the patterns for `definitions` it's not obvious to me which one might be causing the issue (if any are) https://github.com/ionide/ionide-fsgrammar/blob/0100f551f6c32598a58aba97344bf828673fec7a/grammars/fsharp.json#L935

I'll do a bit more hunting when I get time.

**Comment by MangelMaxime** [comment]
Yes working with TextMate grammar is not the easiest things in the world.

In the past my way to trouble shoot things was to either remove portion of the grammar to try find the one causing problems. But this is not always possible when dealing with portion of the grammar that needs others portion to works.

The other solution I had was to add and increment to all the suspected scope and check which increment was reported for the error I was looking at. For example, something like `entity.name.type.fsharp1`, `entity.name.type.fsharp2`, etc.

**Comment by kojo12228** [comment]
Thanks for the suggestion @MangelMaxime, turns out the culprit is this pattern:

https://github.com/ionide/ionide-fsgrammar/blob/0100f551f6c32598a58aba97344bf828673fec7a/grammars/fsharp.json#L425-L432

Now to try and understand what it's trying to do/how it works...
