### ISSUE TITLE
F# highlighting - open namespace not colored correctly when namespace starts with lowercase letter

### ISSUE THREAD

**Issue by rojepp** [ionide/ionide-fsgrammar#22]
<img width="193" alt="screenshot 2017-01-15 18 34 36" src="https://cloud.githubusercontent.com/assets/445888/21965150/3dfcf52a-db5a-11e6-8a75-46a70c88ea23.png">

**Comment by Krzysztof-Cieslak** [comment]
Thanks.

Fix will be available in next Ionide release

**Comment by rojepp** [comment]
Cool, thanks!
