### ISSUE TITLE
'mutable' keyword isn't blue in type definitions

### ISSUE THREAD

**Issue by Phrohdoh** [ionide/ionide-fsgrammar#25]
![screen shot 2017-02-11 at 7 42 49 am](https://cloud.githubusercontent.com/assets/4861023/22854206/e49c3dee-f02e-11e6-9944-dbcb2cfd2ba5.png)

**Comment by cloudRoutine** [comment]
When you find failing cases it's a big help just to PR them into [the sample code source files](https://github.com/ionide/ionide-fsgrammar/tree/master/sample-code) that way anyone working on the grammar can see everything that's broken and if they inadvertently break something.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in https://github.com/ionide/ionide-fsgrammar/commit/7a778ca493ed3c4287fa4e9cc419f7a5618a357c
