### ISSUE TITLE
Comment style isn't applied in parameter list

### ISSUE THREAD

**Issue by Phrohdoh** [ionide/ionide-fsgrammar#26]
```fsharp
let private _emitLetBinding (il:ILGenerator, (*methods:MethodSymbolTable, locals:LocalsSymbolTable,*) binding:LetBinding) =
    let mutable changeset: Changeset = { methods=Map.empty; locals=Map.empty; }

    match binding with
    | Literal (varName, Literal.String strLit) ->
        let localBuilder = il.DeclareLocal(typeof<string>)
        localBuilder.SetLocalSymInfo(varName, 1, 2)
        il.Emit(OpCodes.Ldstr, strLit)
        il.Emit(OpCodes.Stloc_0)

        changeset.locals <- changeset.locals.Add(varName, localBuilder)
    | _ -> ()

    changeset
```

![screen shot 2017-02-11 at 7 57 08 am](https://cloud.githubusercontent.com/assets/4861023/22854257/d033b0de-f02f-11e6-80a5-82a7f28f6a05.png)

**Comment by cloudRoutine** [comment]
When you find failing cases it's a big help just to PR them into [the sample code source files](https://github.com/ionide/ionide-fsgrammar/tree/master/sample-code) that way anyone working on the grammar can see everything that's broken and if they inadvertently break something.
(_am I just copy pasting this onto each issue without a corresponding PR? you know it_ 😜 )
