### ISSUE TITLE
Types and modules are not colored

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-fsgrammar#33]
Reported in; https://github.com/ionide/ionide-vscode-fsharp/issues/207

---

Original comment:

![screenshot from 2016-10-15 17-49-31](https://cloud.githubusercontent.com/assets/873919/19410917/df4544d0-92ff-11e6-8186-d5c3bfe80f1c.png)

_Interesting that they are properly colored in tooltips._

**Comment by MangelMaxime** [comment]
I am not sure to understand what we want to archieve here.

I made a quick gif to have a common code/example to work from

*Source:*

```fs
module LanguageService =

    let parse (fileName : string) = ""

    let declarations (index : int) = ""

type CodeLensProvider =
    abstract provideCodeLenses: document: string * token: int -> obj

let codeLensProvider =
    { new CodeLensProvider with
        member __.provideCodeLenses (doc, token) =
            let parseResult = LanguageService.parse ""
            let declarations = LanguageService.declarations 10
            null
    }
```

![2018-05-25 13 09 20](https://user-images.githubusercontent.com/4760796/40541663-fed5e48a-601c-11e8-9caa-3bfd3fefe50c.gif)

Is the tooltip sentence refering to `module Language` thing when I hover the `LanguageService` word ? And `val parse` when hovering `parse` ?

**Comment by Krzysztof-Cieslak** [comment]
I think suggestion is to have `LanguageService` colored blue (like in module definition). I doubt it's possible to do it accurately with just regexes

**Comment by MangelMaxime** [comment]
Using regexes it will not be possible indeed.

Taking the previous code, we can't handle this case:

```fs
// Type.member
codeLensProvider.provideCodeLenses

// Module.function
LanguageService.parse
```

The case isn't enough to take this decision, because we could have named `CodeLensProvider`.
