### ISSUE TITLE
Coloring issues when union case wraps a record type

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-fsgrammar#35]
Take a look at the following picture. In the definition of `x1`, the `C` case is shown in blue. This is inconsistent with the other examples.

![colorerror](https://user-images.githubusercontent.com/7766733/31760996-c92d0744-b4b6-11e7-91ce-8abe3c16d886.png)

Moved from: https://github.com/ionide/ionide-vscode-fsharp/issues/600

**Comment by MangelMaxime** [comment]
Like mentioned in #51 by using a regex based only syntax highlight we will not be able to fix it.
