### ISSUE TITLE
Change builder detection to whitelisting

### ISSUE THREAD

**Issue by forki** [ionide/ionide-fsgrammar#57]
Currently we treat every function that is followed by { as a builder. The common case that { is a record and not a block is therefore falsely colored. 

I hereby propose we move the error to the builder side and use whitelisting. We should whitelist:
* async
* promise 
* task
* maybe 
* asyncMaybe 
* all Saturn builders like controller

**Comment by Krzysztof-Cieslak** [comment]
We can do this. CC: @MangelMaxime

**Comment by MangelMaxime** [comment]
@Krzysztof-Cieslak Do we have a list of all the Satrun builders ?

Or do I need to look at Saturn code ? I don't know Saturn just quickly read the concept but can't use at work so never gone far ^^
