### ISSUE TITLE
Braces of CEs are colored differently

### ISSUE THREAD

**Issue by inosik** [ionide/ionide-fsgrammar#63]
After #51 the colorization of the opening brace of computation expressions stopped working. I noticed that today.

With 611f9cef099becf192ac50ead122379eeb518d5e (Before merging #51):

![Screenshot: Brace is colored](https://user-images.githubusercontent.com/11393003/40661670-a5033ec2-6354-11e8-89dd-ca875ad263c8.png)

Current `master` of this repository and whatever is in Ionide:

![Screenshot: Brace isn't colored](https://user-images.githubusercontent.com/11393003/40661703-bb8178c6-6354-11e8-93af-7aaf03cf1512.png)

This is how it looks like in VS2013:

![Screenshot: VS2013](https://user-images.githubusercontent.com/11393003/40662247-13a5e2d4-6356-11e8-9de9-7b8e9b0b6923.png)

### Syntax Colorization Failure
```fsharp
let zero = async { return 0 }
```

/cc @MangelMaxime

**Comment by MangelMaxime** [comment]
Good catch, sorry for that.

I am using a custom extension to add color to my braces so I didn't see the problem. I really need to work on the grammar without this extension :)
