### ISSUE TITLE
'of' inside identifier is marked as keyword

### ISSUE THREAD

**Issue by Maxpxt** [ionide/ionide-fsgrammar#69]
### Syntax Colorization Failure

  ![ionide-color-bug](https://user-images.githubusercontent.com/19475500/40801926-95258eb4-64ea-11e8-8ca0-2fe41987f2bc.png)

```fsharp
// Wrong colorization of 'of'
let aofb = ()
aofb
let ofb = ()
ofb
let aof = ()
aof

// Expected colorization
let bla = ()
bla
```

### System Details
- OS: Windows 10
- VSCode 1.23.1
- Installed Extension: Ionide-fsharp 3.21.0

**Comment by MangelMaxime** [comment]
Fixed in https://github.com/ionide/ionide-fsgrammar/pull/67
