### ISSUE TITLE
Incorrect colorization when params are on new line

### ISSUE THREAD

**Issue by selketjah** [ionide/ionide-fsgrammar#82]
When you put the params on a new line of a function, it no longer works.

![image](https://user-images.githubusercontent.com/2250570/42283389-95a6301c-7fa9-11e8-904e-81cb8bc4c9e3.png)

### Syntax Colorization Failure
```fsharp
let example user
            name
            title = 
    ()
```

### System Details
- OS: windows, mac
- vscode 1.24
- v3.22.1

**Comment by MangelMaxime** [comment]
Thanks you for the report. Will try to take a look at it.

Has this been broke by the last Ionide update ?

**Comment by selketjah** [comment]
I cannot confirm that.
It is possible this never worked.
