### ISSUE TITLE
Paket.dependencies grammar

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [ionide/ionide-fsgrammar#9]
![image](https://cloud.githubusercontent.com/assets/5427083/16551842/4f914332-4171-11e6-8f70-e78ef70b29eb.png)

`github` should be only colorized if it's on begging of line (type of dependency)
`git` should be colorized if it's on begging of line (type of dependency)

**Comment by Krzysztof-Cieslak** [comment]
CC: @vbfox

**Comment by vbfox** [comment]
Totally agreed it's the `github` part that appearing in our internal dependencies that motivated me to start rewriting the grammar.

Need to finish it but you can already assign that issue to me

Some of the problems I encountered are that paket parsing code is pretty messy, with special cases and hacks over hacks in some places (Mainly for backward compat) that complexify having a regular grammar over it.

A fun fact for example, if I read the code correctly `lowest_matching` allow an uppercase `TRUE` but `import_targets` doesn't :)
