### ISSUE TITLE
Attributes in function header not highlighted

### ISSUE THREAD

**Issue by forki** [ionide/ionide-fsgrammar#93]
![image](https://user-images.githubusercontent.com/57396/43072635-0983a5e2-8e77-11e8-9645-cd6f9273a2d0.png)

/cc @MangelMaxime 

:hugs:

**Comment by MangelMaxime** [comment]
Yes, I saw it when adding the attributes support and didn't know how to fix it.
I was like, let say no one use it :p

Will try to take a second look at it.

**Comment by MangelMaxime** [comment]
Is it possible to provide me a valid reproduction code ? (with the Attribute defined etc.)

I never used this kind of structure and don't know how to create the attribute type. :)

**Comment by forki** [comment]
See https://github.com/mikhailshilkov/azure-functions-fsharp-examples/blob/master/11-app-attributes/Poll.fs#L46
